a = {    
    "Created by": "sid", 
    "Comment": "Pipe Inputs v1.0", 
    "WARNING": "# WARNING! All changes made in this file will be lost!", 
    "Date": "July:22:2018 - 02:43:01:PM", 
    "Description": "This module contain basic information of pipe steps", 
    "Last modified": "July:22:2018 - 02:43:01:PM", 
    "Author": "Subin. Gopi (subing85@gmail.com)",
    "#Copyright": "(c) 2018, Subin Gopi All rights reserved.", 
    "Valid": True , 
    "Type": "Pipe Input",
      
    "bracket": {    
                    "asset": {  "step": "_asset_",
                                "category": {    "type": "enum", 
                                                "enable": True, 
                                                "order": 1, 
                                                "color": "darkGray", 
                                                "value": 0, 
                                                "values": ["None", "Prop","Character", "Set", "Camera", "Light", "FX", "SetDress",  "PropDress"],
                                                "visibility": True,
                                                "longName": "Catagory"
                                                },                                                
                                "order": 1,
                                "id": "00000",
                                "icon": "ast",
                                "artist": ["Raj", "Subin", "Harikesh"],
                                "status":  ["Not at Start", "WIP", "Correction", "Done", "Approved"],
                                "color": "gray",
                                "shortName": "ast",
                                "longName": "Asset",
                                "startDate": None,
                                "endDate": None,
                                "publish": None,
                                "comment": None,
                                "thumbnail": None
                                },    
                     "shot": {    "step": "_shot_",
                                "category": {    "type": "enum", 
                                                "enable": True, 
                                                "order": 1, 
                                                "color": "darkGray", 
                                                "value": 0, 
                                                "values": ["None", "Layout", "Animation", "Rendering", "Composting"],
                                                "visibility": True,
                                                "longName": "Catagory"
                                                },
                                "order": 2,
                                "id": "00000",
                                "icon": "sht",
                                "artist": ["Raj", "Subin", "Harikesh"],
                                "status":  ["Not at Start", "WIP", "Correction", "Done", "Approved"],
                                "color": "gray",
                                "shortName": "sht",
                                "longName": "Shot",
                                "startDate": None,
                                "endDate": None,
                                "publish": None,
                                "comment": None,
                                "thumbnail": None
                                }
             },           
    "_asset_": {
                "step": {
                            "conceptArt": { "order": 1,
                                            "icon": "cna",                                                        
                                            "color": "darkMagenta",
                                            "shortName": "cna",
                                            "longName": "Concept Art",                                                            
                                            "thumbnail": None,
                                            "visibility": True,    
                                            "enable": True, 
                                            "id": {            "type": "str", 
                                                            "enable": False, 
                                                            "order": 1, 
                                                            "color": "magenta", 
                                                            "value": "00000", 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "ID"
                                                            },
                                            "artist": {        "type": "enum", 
                                                            "enable": True, 
                                                            "order": 2, 
                                                            "color": "magenta", 
                                                            "value": 0, 
                                                            "values":["Raj", "Subin", "Harikesh"],
                                                            "visibility": True,
                                                            "longName": "Artist"                                                    
                                                            },                                            
                                            "status": {        "type": "enum", 
                                                            "enable": True, 
                                                            "order": 3, 
                                                            "color": "magenta", 
                                                            "value": 0, 
                                                            "values": ["Not at Start", "WIP", "Correction", "Done", "Approved"],
                                                            "visibility": True,
                                                            "longName": "Status"
                                                            },
                                            "startDate": {    "type": "str", 
                                                            "enable": True, 
                                                            "order": 4, 
                                                            "color": "magenta", 
                                                            "value": 0, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "Start Date"
                                                            },
                                            "endDate": {    "type": "str", 
                                                            "enable": True, 
                                                            "order": 5, 
                                                            "color": "magenta", 
                                                            "value": 0, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "End Date"                                                            
                                                            },
                                            "publish": {    "type": "enum", 
                                                            "enable": True, 
                                                            "order": 6, 
                                                            "color": "magenta", 
                                                            "value": "0", 
                                                            "values": ["Not Published", "Publish"],
                                                            "visibility": True,
                                                            "longName": "Publish"
                                                            },
                                            "comment": {    "type": "text", 
                                                            "enable": True, 
                                                            "order": 7, 
                                                            "color": "magenta", 
                                                            "value": None, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "Comment"
                                                            },
                                            "version": {    "type": "text", 
                                                            "enable": True, 
                                                            "order": 8, 
                                                            "color": "magenta", 
                                                            "value": None, 
                                                            "values": {"name": "",
                                                                       "owner": "",
                                                                       "publishDate": "",
                                                                       "status": "",
                                                                       "remark": ""},
                                                            "visibility": True,
                                                            "longName": "Version"
                                                        },                                                
                            "modeling": {    "order": 2,
                                            "icon": "mod",                                                            
                                            "color": "darkRed",
                                            "shortName": "mod",
                                            "longName": "Modeling",                                                          
                                            "thumbnail": None,
                                            "visibility": True,    
                                            "enable": True,                                 
                                            "id": {            "type": "str", 
                                                            "enable": False, 
                                                            "order": 1, 
                                                            "color": "red", 
                                                            "value": "00000", 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "ID"
                                                            },                                
                                            "artist": {        "type": "enum", 
                                                            "enable": True, 
                                                            "order": 2, 
                                                            "color": "red", 
                                                            "value": 0, 
                                                            "values":["Raj", "Subin", "Harikesh"],
                                                            "visibility": True,
                                                            "longName": "Artist"
                                                            },                                            
                                            "status": {        "type": "enum", 
                                                            "enable": True, 
                                                            "order": 3, 
                                                            "color": "red", 
                                                            "value": 0, 
                                                            "values": ["Not at Start", "WIP", "Correction", "Done", "Approved"],
                                                            "visibility": True,
                                                            "longName": "Status"
                                                            },
                                            "startDate": {    "type": "str", 
                                                            "enable": True, 
                                                            "order": 4, 
                                                            "color": "red", 
                                                            "value": 0, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "Start Date"
                                                            },
                                            "endDate": {    "type": "str", 
                                                            "enable": True, 
                                                            "order": 5, 
                                                            "color": "red", 
                                                            "value": 0, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "End Date"
                                                            },
                                            "publish": {    "type": "enum", 
                                                            "enable": True, 
                                                            "order": 6, 
                                                            "color": "red", 
                                                            "value": "0", 
                                                            "values": ["Not Published", "Publish"],
                                                            "visibility": True,
                                                            "longName": "Publish"
                                                            },
                                            "comment": {    "type": "text", 
                                                            "enable": True, 
                                                            "order": 7, 
                                                            "color": "red", 
                                                            "value": None, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "Commet"
                                                            },
                                            "version": {    "type": "text", 
                                                            "enable": True, 
                                                            "order": 8, 
                                                            "color": "magenta", 
                                                            "value": None, 
                                                            "values": {"name": "",
                                                                       "owner": "",
                                                                       "publishDate": "",
                                                                       "status": "",
                                                                       "remark": ""},
                                                            "visibility": True,
                                                            "longName": "Version"
                                                        },                                                            
                            "surfacing":{    "order": 3,
                                            "icon": "suf",                                                            
                                            "color": "darkMagenta",
                                            "shortName": "suf",
                                            "longName": "Surfacing",                                                          
                                            "thumbnail": None,
                                            "visibility": True,    
                                            "enable": True,                                 
                                            "id": {            "type": "str", 
                                                            "enable": False, 
                                                            "order": 1, 
                                                            "color": "magenta", 
                                                            "value": "00000", 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "ID"
                                                            },           
                                            "artist": {        "type": "enum", 
                                                            "enable": True, 
                                                            "order": 2, 
                                                            "color": "magenta", 
                                                            "value": 0, 
                                                            "values":["Raj", "Subin", "Harikesh"],
                                                            "visibility": True,
                                                            "longName": "Artist"
                                                            },                                            
                                            "status": {        "type": "enum", 
                                                            "enable": True, 
                                                            "order": 3, 
                                                            "color": "magenta", 
                                                            "value": 0, 
                                                            "values": ["Not at Start", "WIP", "Correction", "Done", "Approved"],
                                                            "visibility": True,
                                                            "longName": "Status"
                                                            },
                                            "startDate": {    "type": "str", 
                                                            "enable": True, 
                                                            "order": 4, 
                                                            "color": "magenta", 
                                                            "value": 0, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "Start Date"
                                                            },
                                            "endDate": {    "type": "str", 
                                                            "enable": True, 
                                                            "order": 5, 
                                                            "color": "magenta", 
                                                            "value": 0, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "End Date"
                                                            },
                                            "publish": {    "type": "enum", 
                                                            "enable": True, 
                                                            "order": 6, 
                                                            "color": "magenta", 
                                                            "value": "0", 
                                                            "values": ["Not Published", "Publish"],
                                                            "visibility": True,
                                                            "longName": "Publish"
                                                            },
                                            "comment": {    "type": "text", 
                                                            "enable": True, 
                                                            "order": 7, 
                                                            "color": "magenta", 
                                                            "value": None, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "Comment"
                                                            },
                                            "version": {    "type": "text", 
                                                            "enable": True, 
                                                            "order": 8, 
                                                            "color": "magenta", 
                                                            "value": None, 
                                                            "values": {"name": "",
                                                                       "owner": "",
                                                                       "publishDate": "",
                                                                       "status": "",
                                                                       "remark": ""},
                                                            "visibility": True,
                                                            "longName": "Version"
                                                        },                                       
                            "sfx": {        "order": 4, 
                                            "icon": "sfx",                                        
                                            "color": "darkGreen",
                                            "shortName": "sfx",
                                            "longName": "FX",
                                            "thumbnail": None,
                                            "visibility": True,    
                                            "enable": True,                                             
                                            "id": {            "type": "str", 
                                                            "enable": False, 
                                                            "order": 1, 
                                                            "color": "green", 
                                                            "value": "00000", 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "ID"
                                                            },                        
                                            "artist": {        "type": "enum", 
                                                            "enable": True, 
                                                            "order": 2, 
                                                            "color": "green", 
                                                            "value": 0, 
                                                            "values":["Raj", "Subin", "Harikesh"],
                                                            "visibility": True,
                                                            "longName": "Artist"
                                                            },                                            
                                            "status": {        "type": "enum", 
                                                            "enable": True, 
                                                            "order": 3, 
                                                            "color": "green", 
                                                            "value": 0, 
                                                            "values": ["Not at Start", "WIP", "Correction", "Done", "Approved"],
                                                            "visibility": True,
                                                            "longName": "Status"
                                                            },
                                            "startDate": {    "type": "str", 
                                                            "enable": True, 
                                                            "order": 4, 
                                                            "color": "green", 
                                                            "value": 0, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "Start Date"
                                                            },
                                            "endDate": {    "type": "str", 
                                                            "enable": True, 
                                                            "order": 5, 
                                                            "color": "green", 
                                                            "value": 0, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "End Date"
                                                            },
                                            "publish": {    "type": "enum", 
                                                            "enable": True, 
                                                            "order": 6, 
                                                            "color": "green", 
                                                            "value": "0", 
                                                            "values": ["Not Published", "Publish"],
                                                            "visibility": True,
                                                            "longName": "Publish"
                                                            },
                                            "comment": {    "type": "text", 
                                                            "enable": True, 
                                                            "order": 7, 
                                                            "color": "green", 
                                                            "value": None, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "Comment"
                                                            },
                                            "version": {    "type": "text", 
                                                            "enable": True, 
                                                            "order": 8, 
                                                            "color": "magenta", 
                                                            "value": None, 
                                                            "values": {"name": "",
                                                                       "owner": "",
                                                                       "publishDate": "",
                                                                       "status": "",
                                                                       "remark": ""},
                                                            "visibility": True,
                                                            "longName": "Version"
                                                        },                           
                            "puppet": {        "order": 5, 
                                            "icon": "pup",                                        
                                            "color": "darkYellow",
                                            "shortName": "pup",
                                            "longName": "Puppet",
                                            "thumbnail": None,
                                            "visibility": True,    
                                            "enable": True, 
                                            "id": {            "type": "str", 
                                                            "enable": False, 
                                                            "order": 1, 
                                                            "color": "yellow", 
                                                            "value": "00000", 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "ID"
                                                            },    
                                            "artist": {        "type": "enum", 
                                                            "enable": True, 
                                                            "order": 2, 
                                                            "color": "yellow", 
                                                            "value": 0, 
                                                            "values":["Raj", "Subin", "Harikesh"],
                                                            "visibility": True,
                                                            "longName": "Artist"
                                                            },                                            
                                            "status": {        "type": "enum", 
                                                            "enable": True, 
                                                            "order": 3, 
                                                            "color": "yellow", 
                                                            "value": 0, 
                                                            "values": ["Not at Start", "WIP", "Correction", "Done", "Approved"],
                                                            "visibility": True,
                                                            "longName": "Status"
                                                            },
                                            "startDate": {    "type": "str", 
                                                            "enable": True, 
                                                            "order": 4, 
                                                            "color": "yellow", 
                                                            "value": 0, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "Start Date"
                                                            },
                                            "endDate": {    "type": "str", 
                                                            "enable": True, 
                                                            "order": 5, 
                                                            "color": "yellow", 
                                                            "value": 0, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "End Date"
                                                            },
                                            "publish": {    "type": "enum", 
                                                            "enable": True, 
                                                            "order": 6, 
                                                            "color": "yellow", 
                                                            "value": "0", 
                                                            "values": ["Not Published", "Publish"],
                                                            "visibility": True,
                                                            "longName": "Publish"
                                                            },
                                            "comment": {    "type": "text", 
                                                            "enable": True, 
                                                            "order": 7, 
                                                            "color": "yellow", 
                                                            "value": None, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "Comment"
                                                            },
                                            "version": {    "type": "text", 
                                                            "enable": True, 
                                                            "order": 8, 
                                                            "color": "magenta", 
                                                            "value": None, 
                                                            "values": {"name": "",
                                                                       "owner": "",
                                                                       "publishDate": "",
                                                                       "status": "",
                                                                       "remark": ""},
                                                            "visibility": True,
                                                            "longName": "Version"
                                                        },                                             
                            "dressing": {    "order": 6,
                                            "icon": "drs",                                            
                                            "color": "darkBlue",
                                            "shortName": "drs",
                                            "longName": "Dressing", 
                                            "thumbnail": None,
                                            "visibility": True,    
                                            "enable": True,
                                            "id": {            "type": "str", 
                                                            "enable": False, 
                                                            "order": 1, 
                                                            "color": "blue", 
                                                            "value": "00000", 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "ID"
                                                            },                                    
                                            "artist": {        "type": "enum", 
                                                            "enable": True, 
                                                            "order": 2, 
                                                            "color": "blue", 
                                                            "value": 0, 
                                                            "values":["Raj", "Subin", "Harikesh"],
                                                            "visibility": True,
                                                            "longName": "Artist"
                                                            },                                            
                                            "status": {        "type": "enum", 
                                                            "enable": True, 
                                                            "order": 3, 
                                                            "color": "blue", 
                                                            "value": 0, 
                                                            "values": ["Not at Start", "WIP", "Correction", "Done", "Approved"],
                                                            "visibility": True,
                                                            "longName": "Status"
                                                            },
                                            "startDate": {    "type": "str", 
                                                            "enable": True, 
                                                            "order": 4, 
                                                            "color": "blue", 
                                                            "value": 0, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "Start Date"
                                                            },
                                            "endDate": {    "type": "str", 
                                                            "enable": True, 
                                                            "order": 5, 
                                                            "color": "blue", 
                                                            "value": 0, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "End Date"
                                                            },
                                            "publish": {    "type": "enum", 
                                                            "enable": True, 
                                                            "order": 6, 
                                                            "color": "blue", 
                                                            "value": "0", 
                                                            "values": ["Not Published", "Publish"],
                                                            "visibility": True,
                                                            "longName": "Publish"
                                                            },
                                            "comment": {    "type": "text", 
                                                            "enable": True, 
                                                            "order": 7, 
                                                            "color": "blue", 
                                                            "value": None, 
                                                            "values": None,
                                                            "visibility": False,
                                                            "longName": "Comment"
                                                            },
                                            "version": {    "type": "text", 
                                                            "enable": True, 
                                                            "order": 8, 
                                                            "color": "magenta", 
                                                            "value": None, 
                                                            "values": {"name": "",
                                                                       "owner": "",
                                                                       "publishDate": "",
                                                                       "status": "",
                                                                       "remark": ""},
                                                            "visibility": True,
                                                            "longName": "Version"
                                                        }
                                        }                                                          
                            }                           
                },    
    "_shot_": {    
                "step": {
                            "layout": {        "order": 1,
                                            "icon": "lot",
                                            "color": "darkCyan",
                                            "shortName": "lot",
                                            "longName": "Layout",
                                            "thumbnail": None,
                                            "movie": None,
                                            "visibility": True,    
                                            "enable": True, 
                                            "id": {            "type": "str", 
                                                            "enable": False, 
                                                            "order": 1, 
                                                            "color": "cyan", 
                                                            "value": "00000", 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "ID"
                                                            },    
                                            "artist": {        "type": "enum", 
                                                            "enable": True, 
                                                            "order": 2, 
                                                            "color": "cyan", 
                                                            "value": 0, 
                                                            "values":["Raj", "Subin", "Harikesh", "Krish"],
                                                            "visibility": True,
                                                            "longName": "Artist"
                                                            },                                            
                                            "status": {        "type": "enum", 
                                                            "enable": True, 
                                                            "order": 3, 
                                                            "color": "cyan", 
                                                            "value": 0, 
                                                            "values": ["Not at Start", "WIP", "Correction", "Done", "Approved"],
                                                            "visibility": True,
                                                            "longName": "Status"
                                                            },
                                            "startDate": {    "type": "str", 
                                                            "enable": True, 
                                                            "order": 4, 
                                                            "color": "cyan", 
                                                            "value": 0, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "Start Date"
                                                            },
                                            "endDate": {    "type": "str", 
                                                            "enable": True, 
                                                            "order": 5, 
                                                            "color": "cyan", 
                                                            "value": 0, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "End Date"
                                                            },
                                            "publish": {    "type": "enum", 
                                                            "enable": True, 
                                                            "order": 6, 
                                                            "color": "cyan", 
                                                            "value": "0", 
                                                            "values": ["Not Published", "Publish"],
                                                            "visibility": True,
                                                            "longName": "Publish"
                                                            },
                                            "comment": {    "type": "text", 
                                                            "enable": True, 
                                                            "order": 7, 
                                                            "color": "cyan", 
                                                            "value": None, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "Comment"
                                                            },
                                            "version": {    "type": "text", 
                                                            "enable": True, 
                                                            "order": 8, 
                                                            "color": "magenta", 
                                                            "value": None, 
                                                            "values": {"name": "",
                                                                       "owner": "",
                                                                       "publishDate": "",
                                                                       "status": "",
                                                                       "remark": ""},
                                                            "visibility": True,
                                                            "longName": "Version"
                                                        },                                          
                            "animation": {    "order": 2,
                                            "icon": "ani",                                            
                                            "color": "darkRed",
                                            "shortName": "ani",
                                            "longName": "Animation",
                                            "thumbnail": None,
                                            "movie": None,
                                            "visibility": True,    
                                            "enable": True, 
                                            "id": {            "type": "str", 
                                                            "enable": False, 
                                                            "order": 1, 
                                                            "color": "red", 
                                                            "value": "00000", 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "ID"
                                                            },                                            
                                            "artist": {        "type": "enum", 
                                                            "enable": True, 
                                                            "order": 2, 
                                                            "color": "red", 
                                                            "value": 0, 
                                                            "values":["Raj", "Subin", "Harikesh", "Krish"],
                                                            "visibility": True,
                                                            "longName": "Artist"
                                                            },                                            
                                            "status": {        "type": "enum", 
                                                            "enable": True, 
                                                            "order": 3, 
                                                            "color": "red", 
                                                            "value": 0, 
                                                            "values": ["Not at Start", "WIP", "Correction", "Done", "Approved"],
                                                            "visibility": True,
                                                            "longName": "Status"
                                                            },
                                            "startDate": {    "type": "str", 
                                                            "enable": True, 
                                                            "order": 4, 
                                                            "color": "red", 
                                                            "value": 0, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "Start Date"
                                                            },
                                            "endDate": {    "type": "str", 
                                                            "enable": True, 
                                                            "order": 5, 
                                                            "color": "red", 
                                                            "value": 0, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "End Date"
                                                            },
                                            "publish": {    "type": "enum", 
                                                            "enable": True, 
                                                            "order": 6, 
                                                            "color": "red", 
                                                            "value": "0", 
                                                            "values": ["Not Published", "Publish"],
                                                            "visibility": True,
                                                            "longName": "Publish"
                                                            },
                                            "comment": {    "type": "text", 
                                                            "enable": True, 
                                                            "order": 7, 
                                                            "color": "red", 
                                                            "value": None, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "Comment"
                                                            },
                                            "version": {    "type": "text", 
                                                            "enable": True, 
                                                            "order": 8, 
                                                            "color": "magenta", 
                                                            "value": None, 
                                                            "values": {"name": "",
                                                                       "owner": "",
                                                                       "publishDate": "",
                                                                       "status": "",
                                                                       "remark": ""},
                                                            "visibility": True,
                                                            "longName": "Version"
                                                        },                                               
                            "rendering":{    "order": 3,
                                            "icon": "rnd",                                            
                                            "color": "darkMagenta",
                                            "shortName": "rnd",
                                            "longName": "Rendering",
                                            "thumbnail": None,
                                            "movie": None,    
                                            "visibility": True,    
                                            "enable": True,                                             
                                            "id": {            "type": "str", 
                                                            "enable": False, 
                                                            "order": 1, 
                                                            "color": "red", 
                                                            "value": "00000", 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "ID"
                                                            }, 
                                            "artist": {        "type": "enum", 
                                                            "enable": True, 
                                                            "order": 2, 
                                                            "color": "magenta", 
                                                            "value": 0, 
                                                            "values":["Raj", "Subin", "Harikesh", "Krish"],
                                                            "visibility": True,
                                                            "longName": "Artist"
                                                            },                                            
                                            "status": {        "type": "enum", 
                                                            "enable": True, 
                                                            "order": 3, 
                                                            "color": "magenta", 
                                                            "value": 0, 
                                                            "values": ["Not at Start", "WIP", "Correction", "Done", "Approved"],
                                                            "visibility": True,
                                                            "longName": "Status"
                                                            },
                                            "startDate": {    "type": "str", 
                                                            "enable": True, 
                                                            "order": 4, 
                                                            "color": "magenta", 
                                                            "value": 0, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "Start Date"
                                                            },
                                            "endDate": {    "type": "str", 
                                                            "enable": True, 
                                                            "order": 5, 
                                                            "color": "magenta", 
                                                            "value": 0, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "End Date"
                                                            },
                                            "publish": {    "type": "enum", 
                                                            "enable": True, 
                                                            "order": 6, 
                                                            "color": "magenta", 
                                                            "value": "0", 
                                                            "values": ["Not Published", "Publish"],
                                                            "visibility": True,
                                                            "longName": "Publish"
                                                            },
                                            "comment": {    "type": "text", 
                                                            "enable": True, 
                                                            "order": 7, 
                                                            "color": "magenta", 
                                                            "value": None, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "Comment"
                                                            },
                                            "version": {    "type": "text", 
                                                            "enable": True, 
                                                            "order": 8, 
                                                            "color": "magenta", 
                                                            "value": None, 
                                                            "values": {"name": "",
                                                                       "owner": "",
                                                                       "publishDate": "",
                                                                       "status": "",
                                                                       "remark": ""},
                                                            "visibility": True,
                                                            "longName": "Version"
                                                        }, 
                            "composting": {    "order": 4,
                                            "icon": "cop",                                            
                                            "color": "darkGreen",
                                            "shortName": "cop",
                                            "longName": "Composting",
                                            "thumbnail": None,
                                            "movie": None,
                                            "visibility": True,    
                                            "enable": True,                                             
                                            "id": {            "type": "str", 
                                                            "enable": False, 
                                                            "order": 1, 
                                                            "color": "green", 
                                                            "value": "00000", 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "ID"
                                                            }, 
                                            "artist": {        "type": "enum", 
                                                            "enable": True, 
                                                            "order": 2, 
                                                            "color": "green", 
                                                            "value": 0, 
                                                            "values":["Raj", "Subin", "Harikesh", "Krish"],
                                                            "visibility": True,
                                                            "longName": "Artist"
                                                            },                                            
                                            "status": {        "type": "enum", 
                                                            "enable": True, 
                                                            "order": 3, 
                                                            "color": "green", 
                                                            "value": 0, 
                                                            "values": ["Not at Start", "WIP", "Correction", "Done", "Approved"],
                                                            "visibility": True,
                                                            "longName": "Status"
                                                            },
                                            "startDate": {    "type": "str", 
                                                            "enable": True, 
                                                            "order": 4, 
                                                            "color": "green", 
                                                            "value": 0, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "Start Date"
                                                            },
                                            "endDate": {    "type": "str", 
                                                            "enable": True, 
                                                            "order": 5, 
                                                            "color": "green", 
                                                            "value": 0, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "End Date"
                                                            },
                                            "publish": {    "type": "enum", 
                                                            "enable": True, 
                                                            "order": 6, 
                                                            "color": "green", 
                                                            "value": "0", 
                                                            "values": ["Not Published", "Publish"],
                                                            "visibility": True,
                                                            "longName": "Publish"
                                                            },
                                            "comment": {    "type": "text", 
                                                            "enable": True, 
                                                            "order": 7, 
                                                            "color": "green", 
                                                            "value": None, 
                                                            "values": None,
                                                            "visibility": True,
                                                            "longName": "Publish"                                                            
                                                            },
                                            "version": {    "type": "text", 
                                                            "enable": True, 
                                                            "order": 8, 
                                                            "color": "magenta", 
                                                            "value": None, 
                                                            "values": {"name": "",
                                                                       "owner": "",
                                                                       "publishDate": "",
                                                                       "status": "",
                                                                       "remark": ""},
                                                            "visibility": True,
                                                            "longName": "Version"
                                                         }
                                        }                                             
                            }                           
                }    
}